template = "{company}\nLEASE AGREEMENT\nTHIS LEASE AGREEMENT, dates this {date} day of {month_year}, is made between {landlord} (\"Landlord\") and {tenant} (\"Tenant\").\n\
            1. SUMMARY OF BASIC LEASE PROVISIONS. The following is a summary of the basic terms of this Lease.  In all instances, the basic terms set forth in this Section 1 are subject to the main body of the Lease in general, and to those sections noted in parentheses in particular.\n\
            1.1 TENANT'S NAME AND ADDRESS: {tenant_name_address}\n\
            1.2 PREMISES ADDRESS {premises_address}\n\
            1.3 LEASE TERM: {lease_term}\n\
            1.4 COMMENCEMENT DATE: {commencement_date}\n\
            1.5 LEASE END DATE: {lease_end}\n\
            1.6 BASE RENT: {base_rent}\n\
            1.7 ADDITIONAL RENT: {additional_rent}\n\
            1.8 TERMINATION OPTION: {termination_option}\n\
            1.9 OPTION RENT: {option_rent}\n\
            1.10 TENANT'S USE: {tenant_use}\n\
            1.11 SECURITY DEPOSIT: {security_deposit}\n\
            1.12 PREPAID RENT: {prepaid_rent}\n\
            2. DEFINITIONS.\n\
            2.1 Additional  Rent.  \"Additional Rent\" shall mean all sums and charges payable under this Lease in addition to Base Rent.\n\
            2.2 Base Rent - Section 5.1\n\
            2.3 Buildings.  The term \"Buildings\" shall mean {buildings}\n\
            2.4 Commencement Date.  The term \"Commencement Date\" shall mean the day the Lease Term commences, which shall be the date set forth in Section 1.4, above.\n\
            2.5 Common Areas.  The term \"Common Areas\" shall mean any area within the Buildings or on or about the Property designated by the Landlord as being for the use generally of tenants, patrons, employees and invitees of the Buildings and shall include parking areas, landscaped areas, service and utility areas, walks, public stairs, elevators, corridors or other shared areas or spaces.\n\
            2.6 Hazardous Substances. The term \"Hazardous Substance\" means any substance that is toxic, ignitable, reactive or corrosive and that is regulated by any local government, the State of Washington, or the United States Government.  \"Hazardous Substance\" includes any and all material or substances that are defined as \"hazardous waste,\" \"extremely hazardous waste,\" or a \"hazardous substance\" pursuant to state, federal or local governmental law.  \"Hazardous Substance\" includes but is not restricted to asbestos, polychlorobiphenyls (\"PCBs\") and petroleum.\n\
            2.7 Land. The term \"Land\" shall mean the real property on which the Buildings and related improvements are located.  The Land is legally described on Exhibit A hereto.\n\
            2.8 Landlord's Insurance - Section 9.1\n\
            2.9 Lease Term - Section 4\n\
            2.10 Lease Year.  The term \"Lease Year\" as used herein shall mean each twelve (12) month period following the Commencement Date; provided, however, that if the Commencement Date is the first day of a month, the first Lease Year shall be deemed to include any partial month at the beginning of the Lease Term.\n\
            2.11 Operating Expenses - Section 5.2\n\
            2.12 Premises. The term \"Premises\" shall mean approximately {premises} of rentable area within the Buildings, as shown on the Site Plan attached hereto as Exhibit B.\nCommon Areas of Property are for the common, non-exclusive use of all tenants and customers. Tenant shall take no action to interfere with the common usage of all such areas.\n\
            2.13 Property.  The term \"Property\" shall mean the Land, Buildings, and all other improvements located on the land.\n\
            2.14 Rent. The term \"Rent\" shall mean the sum of Base Rent and all Additional Rent payable by Tenant to Landlord hereunder.\n\
            2.15 Self Insurance Amount - Section 9.2.3\n\
            2.16 Tenant. The term \"Tenant\" shall be deemed to include Tenant and its subtenants, concessionaires and any person occupying the whole or any part of the leased Premises.\n\
            2.17 Tenant's Certificate - Section 18.3\n\
            2.18 Tenant's Insurance - Section 9.2\n\
            2.19 Tenant's Work - Section 3.2\n\
            3. PREMISES AND MODIFICATION TO PREMISES.\n\
            3.1 Lease of Premises.  Landlord hereby leases the Premises to Tenant, and Tenant hereby leases the Premises from Landlord, subject to an in accordance with the remaining terms and conditions of this Lease.\n\
            3.2 Tenant’s Work. Any modifications or alterations to the Premises desired by Tenant shall be performed by Tenant, at Tenant's cost and expense, in accordance with plans and specifications approved in writing by Landlord prior to commencement of work (“Tenant’s Work”).  Tenant's space plan shall also require the Landlord's prior approval.  Landlord's approval under this Section 3.2 shall not be unreasonably withheld and shall be deemed given if not denied in writing within ten (10) days after Tenant's written request is delivered to Landlord, accompanied by detailed plans and specifications.  All work shall be done in a good and workmanlike manner.  Tenant shall keep the Premises free and clear of liens or charges for labor and materials furnished for Tenant's Work and provide Landlord with copies of lien waivers from Tenant's general contractor.  All of Tenant's Work shall meet the requirements of public authorities.  Tenant shall utilize its own contractor and architect, shall pay all costs, and fees, and shall obtain all permits and governmental approvals for its design and construction.  Upon completion of any Tenant's Work, Tenant shall provide Landlord with a complete set of \"as built\" drawings.\n\
            3.3 Modification by Landlord.  The Premises are leased to the Tenant “As Is” except as set forth in Exhibit “F” if any (“Landlord’s work”).\n\
            4. TERM. The term of this Lease shall begin on the Commencement Date and end on the last day of the month set forth in Section  1.5 (\"Lease Term\")\n\
            4.1 Option to Terminate. Tenant shall have the ongoing right to terminate the Lease at any time with 180 days written notice.\n\
            4.2 Holdover Rent. In the event Tenant remains in the Premises after the effective date of termination of the Lease, the Base Rent during the holdover period shall be 125% of the most recent Base Rent payable prior to the effective date of termination, unless otherwise agreed in writing.\n\
            4.3 Cease Operations. INTENTIONALLY OMITTED.\n\
            5. RENT. Base Rent and Operation Expenses shall be payable as follows:\n\
            5.1 Base Rent. Tenant covenants and agrees to pay to Landlord in advance by the first (1st) day of each calendar month, and without offset or deduction of any kind, minimum rent (“Base Rent”) as follows:  Commencing upon the Commencement Date, the amount set forth in Section 1.6 during the first Lease Year.  Late charges pursuant to Section 16.5 shall be assessed for failure to pay Rent on or before the tenth (10th) day of each month.  Commencing on the first day of the second Lease Year, and on the first day of each Lease Year thereafter during the Lease Term, Base Rent shall increase for the ensuing Lease Year by 3% of the Base Rent last in effect during the preceding Lease Year.   The Base Rent is set forth as follows:\n{base_rent}\n\
            5.1.1 Payment of Rent. Until further notice by Landlord to Tenant, rent payments shall be payable and delivered to:\n{pay_to}\n\
            5.1.2 Pro Rata Base Rent.  If the commencement date of the Term of this Lease occurs on a day other than the first (1st) day of a calendar month, the Base Rent at the monthly rate shall be prorated upon the basis which the number of days of the Term of this Lease in such month bears to the total number of days in such month, and as so prorated shall be paid forthwith upon the Commencement Date.\n\
            5.2 Additional Rent.  Upon the Commencement Date, Tenant covenants and agrees to pay, as Additional Rent, it’s pro rata share of Operating Expenses.  Tenant's share shall be in the same proportion as the net rentable square foot floor area of the Premises is to the net rentable square foot floor area of the Buildings, subject to adjustments for any special circumstances, which may affect Tenant’s pro rata, allocation. Upon commencement of the Lease, Tenant's pro rata share is estimated to be approximately {pro_rata1}. Such amounts shall be billed to Tenant on a monthly basis as provided in Section 5.2.3.  The square footage of the Premises and the Buildings set forth in Sections 2.12 and 2.3 are conclusively deemed to be the actual square footage thereof, without regard to any subsequent remeasurement of the Premises or the Buildings.\n\
            5.2.1 Operating Expenses. All costs, fees and expenses that are incurred by Landlord or its agents in operating, insuring, repairing, replacing and maintaining of the Premises and the Property shall be referred to as \"Operating Expenses.\" Operating Expenses shall include the following, subject to exclusions set forth in Section 5.2.2:\n\
            (1) All real estate taxes, L.I.D. assessments, any rental tax or assessment, or other costs, charges or fees imposed by any governmental authority in connection with the Property.\n\
            (2) Costs of all insurance relating to the Premises and the Property, including coverage for, without limitation, property, casualty, differences in conditions, and rental abatement, as provided in Section 9.  Such insurance to be of a form, kind and coverage amount and with insurers reasonably determined by Landlord.\n\
            (3) Common Area utilities, snow removal, trash or debris removal, security devices and services all accounting, legal and professional fees incurred in connection with the operation of the Property, third party property management fees not to exceed five percent (5%) of Base Rent, services of independent contractors and compensation of all persons who perform duties of operation, maintenance and repair of the Buildings and Common Areas.\n\
            (4) All costs and fees of operating, maintaining and repairing the Common Areas of the Buildings and the Property, including:  lighting, heating, air conditioning, cleaning, drainage, painting, repaving, resurfacing and restriping parking lots (but not rebuilding), sidewalks, walls, fences, driveways, landscaping (including replacing trees, plants and shrubs), fire sprinkler and/or alarm system, irrigation system, water and sewer lines, storm drains, security, signs, glass, restrooms, roof surface, plywood and membrane, awnings, canopies, and all other Common Areas, excepting the structural integrity of the side walls, roof and foundation of the Buildings.\n\
            (5) All costs and fees for repairing, replacing and maintaining the fixtures, improvements, mechanical, electrical and plumbing equipment and systems, including service contracts, supplies, materials, tools and equipment, for all such items presently existing or subsequently installed in the Common Areas.\n\
            (6) Reasonable reserves for roof replacement based on a 15-year usable life; HVAC replacement, based on a 10-year usable life; building painting, and parking lot resurfacing and restriping based on a 5-year useable life.\n\
            The preceding items are by way of example and do not exclude other costs, charges or expenses which may be incurred during the Lease Term, all of which shall be paid by the Landlord on the prorated basis described above.\n\
            Notwithstanding, Tenant shall pay all costs associated with Tenant's own occupancy of the Premises, including Tenant's janitorial services, utilities including electric, water/sewer, garbage, gas, separately metered utilities and any surcharge for excess water and sewer use, if applicable, to Tenant’s use of the Premises. Tenant shall reimburse Landlord for these operating expenses as Additional Rent and shall pay a pro-rated share of the utilities estimated to be approximately {pro_rata2}.\n\
            5.2.2 Exclusions From Operating Expenses. The following items shall not be included in the Operating Expenses for which the Tenant pays its pro rata share:\n\
            (1) Initial construction of the Buildings or other improvements on the Property or any expansion thereof or costs of correcting any construction defect;\n\
            (2) Interest on payments of any financing for the Property;\n\
            (3) Repair or replacement of structural portions of the roof, sidewalls, and foundation;\n\
            (4) Legal fees, leasing commissions, advertising expenses and other costs in connection with the leasing of the Buildings;\n\
            (5) Costs of preparing or renovating spaces for other tenants;\n\
            (6) Any item for which Landlord is reimbursed by insurance or warranty or condemnation award;\n\
            (7) Cost or depreciation of capital improvements to the Property, unless an asset is installed or replaced (rather than repaired) in order to achieve cost efficiency which inures to the benefit of the Tenant in lower operating or repair costs for the Property;\n\
            (8) Costs associated with the operation of the Landlord's entity as opposed to the cost of maintaining the Buildings and Common Areas;\n\
            (9) Interest or penalties incurred as result of Landlord's failing to pay a bill as the same shall become due;\n\
            (10) Cost of renting or leasing any item if the purchase price would not properly be included as a reimbursable expense, excepting temporary rental of equipment to perform maintenance, repair or replacement of fixtures, improvements, equipment and systems;\n\
            (11) Costs associated with remediation, disposal or cleanup of Hazardous Substances excepting such costs resulting from acts or omissions of any kind by the Tenant or Tenant's agents, employees, contractors, licensees or invitees; and\n\
            (12) Costs incurred because of Landlord's negligence or breach of any legal obligation or the breach of any legal obligation by any other tenant in the Buildings.\n\
            5.2.3 Statement of Operating Expenses. Upon the commencement of Rent, the Landlord shall submit to Tenant a statement of Landlord’s estimate of the monthly Operating Expenses for the current calendar year.  Tenant shall pay the same and all subsequent monthly payments concurrently with the payment of Base Rent.  Tenant shall continue to make the monthly payments until notified by Landlord of a change in the amount.\
                {operating_expenses_date}, Landlord shall give Tenant a statement showing the actual total Operating Expenses for the Premises for the prior calendar year and the Tenant’s allocable share thereof.  In the event that the total of the monthly payments which Tenant has made for the prior calendar year are less than the Tenant's actual share of the Operating Expenses, Tenant shall pay the difference in a lump sum within ten (10) days after receipt of a statement from Landlord.  Any overpayment by Tenant shall be credited toward the monthly rent next coming due or refunded at the time Landlord issues its final statement to Tenant.  In any year in which substantial maintenance or repair is contemplated, Landlord shall be permitted to include the anticipated cost of same as part of the estimated monthly Operating Expenses.  Even though the Lease Term has expired and Tenant has vacated the Premises, when the final determination is made of Tenant's share of the Operating Expenses for the year in which this Lease terminates, Tenant shall immediately pay the amount due for any increase over the estimated Operating Expenses previously paid and, conversely, any overpayment made shall be immediately rebated by Landlord to Tenant.\n\
            The statements of Operating Expenses furnished by Landlord or Landlord's agent shall be reasonably detailed. Landlord shall keep good and accurate books and records concerning Operating Expenses in accordance with generally accepted accounting principles. Tenant shall have the right, during reasonable business hours and upon not less than ten (10) days' prior written notice to Landlord, to examine the Landlord’s records with respect to the foregoing at Tenant's expense.  Landlord shall provide copies of invoices and receipts in support of the records examination.\n\
            5.3 Security and Damage Deposit.  The Tenant shall pay a security and damage deposit in the amount set forth in Section 1.11 upon execution of this Lease.  Such sum shall be held by Landlord as security for the faithful performance by Tenant of all of its obligations under this Lease.  The deposit shall not be assigned, transferred or encumbered by Tenant, and any attempt to do so by Tenant shall not be binding upon Landlord.\n\
            5.3.1 Use of Deposit During Lease.  If Tenant defaults with respect to any provision of this Lease, or should Landlord make any payment on behalf of Tenant, Landlord may (but shall not be required to) use, apply or retain all or any part of the deposit for the payment of any other amount which Landlord may spend or become obligated to spend by reason of Tenant's default, or to compensate Landlord for any other loss or damage which Landlord has suffered or may suffer by reason of Tenant's default.  If any portion of said deposit is so used, applied or retained, Tenant shall forthwith upon Landlord's demand therefore, deposit cash with Landlord in an amount sufficient to restore said deposit to its original sum.  Tenant's failure to do so shall constitute a material breach of this Lease.\n\
            5.3.2 Landlord shall not be required to keep the deposit separate from its general funds and is in no event to be deemed a trustee thereof; and Tenant shall not be entitled to interest on any sums deposited or redeposited under this Section.  If Tenant shall have fully and faithfully performed all of its obligations under this Lease, the deposit or its then remaining balance shall be refunded to Tenant within thirty (30) days after the termination of this Lease.  In the event Landlord's interest in this Lease is sold or otherwise terminated, Landlord shall transfer the deposit to its successor in interest, and thereupon Landlord shall be discharged from any further liability with respect thereto.  The provisions of the preceding sentence shall likewise apply to any subsequent transferees.\n\
            5.4 {5_4}\n\
            6. TENANT'S USE OF PREMISES.\n\
            6.1 Use. Tenant shall use and occupy the Premises only for the purposes set forth in Section 1.10, above, and for no other use or purpose without the prior written consent of Landlord.\n\
            6.2 Prohibitions.  Tenant shall not permit damage to the Premises.  Tenant shall not do anything which may be a nuisance.  Tenant shall keep the Premises clean and free from rubbish and shall store all trash and garbage within the Premises or within areas designated by Landlord for such purposes.  Tenant shall not burn any trash of any kind in or about the Premises.  Tenant shall not permit the emission of unreasonable odors from the Premises.  All medical waste, biological and chemical substances shall be disposed of in a lawful manner. Tenant shall have not patients, customers, or employees lingering outside the premises.\n\
            6.3 Deliveries.  All deliveries of merchandise, supplies and materials to the Premises and removal of trash, garbage and other waste shall be made at reasonable hours.  Tenant will not permit an accumulation of boxes, waste or other refuse matter.\n\
            6.4 Compliance With Law.  Tenant, at its expense, shall promptly comply with all present and future laws, and requirements of all governmental authorities having jurisdiction, affecting or applicable to the Premises or the cleanliness, safety, occupancy and use of the same.  If any governmental license or permit shall be required for the proper and lawful conduct of Tenant's business or other activity carried on from the Premises, then Tenant, at its expense, shall duly procure and thereafter maintain such license or permit.\n\
            6.5 Indemnity.  Tenant hereby agrees to indemnify, defend and hold the Landlord harmless from any liability, claim, damage or expense (including reasonable attorney’s fees and expenses of litigation) resulting from Tenant's use of the Premises, as well as any fines or penalties resulting from Tenant’s use, storage or disposal of any Hazardous Substances on or about the Premises or Property in violation of applicable law.  This indemnification shall not apply to injuries to persons or damages to property arising from the gross negligence or willful misconduct of the Landlord or its agents or contractors.\n\
            6.6 Restricted Uses.  Tenant acknowledges that exclusive uses may have been granted to other tenants or are restricted within the Buildings.    Any such current exclusive use rights and/or use restrictions are set for on Exhibit C attached hereto. Tenant and any permitted successor assignee or subtenant shall not engage in such unless such uses or restrictions are expressly waived in writing by Landlord in its sole discretion.  Additional exclusive or restricted uses may be imposed by Landlord, from time to time, during the Lease Term.\n\
            7. MORTGAGES AND ENCUMBRANCES.\n\
            7.1 Mortgages.  This Lease is subordinate to any mortgages or deeds of trust now or hereafter affecting the Premises, subject to Tenant’s receipt of commercially reasonable non-disturbance protections.\n\
            7.2 Encumbrances.  The Tenant shall not permit liens, encumbrances or UCC filings against the real or personal property owned by the Landlord, including furniture, fixtures and equipment presently existing or subsequently installed by the Landlord.\n\
            8. TENANT'S OBLIGATIONS WITH RESPECT TO THE PREMISES.\n\
            8.1 Interior Fixtures.  Prior to the installation or replacement of Tenant's Improvements, Tenant shall submit a plan to Landlord for its written approval, which shall not be unreasonably withheld and shall be deemed given if not denied in writing within ten (10) days after Tenant's written request is delivered to Landlord, accompanied by detailed plans and specifications.  Tenant shall pay all taxes or assessments on furniture, fixtures, and equipment presently existing or subsequently added by Tenant.\n\
            8.2 Exterior Fixtures.  Tenant shall not install exterior lighting fixtures, shades or awnings or do any exterior decoration or painting, or make any structural alterations to the Premises without the prior written consent of Landlord and applicable approvals from governmental authorities.  Landlord's consent shall not be unreasonably withheld and shall be deemed given if not denied in writing within ten (10) days after Tenant's written request is delivered to Landlord, accompanied by detailed plans and specifications.\n\
            8.3 Tenant to Provide Conforming Signs.  Tenant agrees, at its own expense, to utilize signs approved by Landlord and the applicable governmental authorities, and to install and thereafter maintain in good condition the signs so approved.  All signs shall also require the Landlord’s prior approval and shall be consistent with signage for the Buildings.\n\
            8.4 Mechanic's Liens.  Tenant agrees that it will pay all costs for work done by it to the Premises, and Tenant will keep the Premises and the Property free from all mechanic's liens and other liens on account of work done for Tenant or persons claiming under it.\n\
            8.4.4 Notice of Liens.  Should any claim of lien be filed against the Premises or any action affecting the title to the Property be commenced, upon receiving notice of such lien or action, Tenant shall immediately give Landlord written notice thereof.  Tenant shall deposit with Landlord, in escrow, an amount equal to 110% of the lien amount.  Landlord shall disburse such escrowed funds upon written instructions from Tenant or a court order.  If such a deposit is not made after Landlord’s demand, the Landlord may take all action Landlord deems appropriate to remove the lien.\n\
            8.4.5 Tenant's Liens.  In the event that, as a result of work performed by Tenant, a dispute between Tenant and a mechanic, materialman or other third party having lien rights arises, which in turn result in litigation to perfect and enforce such lien right in which Landlord or any party deriving rights from Landlord is named a party defendant, then defense of such action shall, at Landlord's option, immediately be assumed by Tenant, and Tenant shall appear and defend Landlord and such deriving parties or shall pay any costs or reasonable attorney's fees incurred by Landlord or such deriving parties in respect to their own defenses to such action; Tenant further shall indemnify and hold Landlord and such parties harmless from any judgment arising out of such litigation.  In addition, Tenant shall reimburse Landlord for any costs or reasonable attorney's fees incurred by Landlord in establishing its right to indemnity under this Section.\n\
            8.5 Utilities.  Tenant shall pay when due and directly to the appropriate utility company all bills for separately metered utilities in the Premises. If common area utility use is exceptionally higher than would be for a Tenant with a similar business than Landlord reserves the right to bill back Tenant for the excess usage.\n\
            8.6 General Maintenance.  Tenant shall make repairs to the interior of the Premises to maintain the Premises in first class condition, at Tenant’s expense.  Tenant shall provide its own janitorial services.  Tenant’s responsibility shall include proper cleaning and maintenance of its storefront and adjacent sidewalk.\n\
            8.7 Compliance with Public Authorities.  Tenant shall comply with the valid requirements of public authorities regarding the manner of the conduct of Tenant's business in the Premises.  Tenant shall make all changes or installations and pay the costs of all inspections required to comply with valid requirements of public authorities as they apply to the Premises during the Lease Term, which are a result of Tenant's particular use of, or modification to, the Premises.\n\
            9. INSURANCE.\n\
            9.1 Landlord's Insurance.  Landlord shall carry such insurance coverage as it deems appropriate in its reasonable discretion including “property” (direct physical damage insurance), “casualty” (third-party legal liability insurance) and “differences in conditions” (“Landlord’s Insurance”).  Landlord’s Insurance shall utilize forms and policies or endorsements as Landlord shall determine.  The Landlord anticipates “Special Form Coverage” (commonly referred to as all perils), with differences in conditions form and coverage for earth movement, ordinance or law, loss of rents, interruption of business, power interruption/failure, and damage from backing up sewers, drains or groundwater, at replacement cost including demolition (without deduction for depreciation) and commercial general liability coverage with limits of not less than Three Million Dollars ($3,000,000) per occurrence, combined single limit for bodily injury and/or property damage.  Terrorism coverage shall be included if required by any mortgage lender for the Property.\n\
            Tenant shall pay its pro rata share of Landlord's Insurance as an Operating Expense.\n\
            9.2 Tenant Insurance.\n\
            9.2.1 Workers’ Compensation.  Tenant shall maintain all required coverages including Employer’s Liability with a limit of not less than One Million Dollars ($1,000,000).\n\
            9.2.2 Liability Insurance.  Tenant shall, throughout the term of this Lease and any renewal hereof, at its own expense, keep and maintain in full force and effect, a policy of Commercial General Liability insurance on an occurrence form, including Premises & Operations, Blanket Contractual Products/Completed Operations; Owners’ and Contractors’ Protective, Employer’s Contingent Liability and Personal Injury, insuring Tenant’s activities upon, in or about the Premises or the Property against claims of bodily injury or death or property damage or loss with a combined single limit of not less than One Million Dollars ($1,000,000) per occurrence.  Landlord and property manager shall be named as Additional Insureds.  All insurers shall have a Best’s rating of AV or better and be licensed and admitted in the State of Washington.\n\
            Tenant shall deliver to Landlord prior to occupancy and at least annually thereafter, copies of policies of such insurance or certificates evidencing the existence of the minimum required insurance and evidencing Landlord and property manager as Additional Insured thereunder.  In no event shall the limits of any insurance policy required under this Section be considered as limiting the liability of Tenant under this lease.\n\
            All policies required under this Section shall be written:  (1) as primary policies and not contributing to or in excess of any coverage Landlord may choose to maintain; and (2) on occurrence liability basis (not “claims made”).\n\
            9.2.3 The insurance required to be maintained by Tenant pursuant to this Lease may be maintained under a plan of self-insurance; provided, however, that Tenant shall be entitled to utilize such self-insurance only for such periods as Tenant’s tangible net worth, as shown on its most recently published, audited financial statements (or, if no such statement exists, as certified by its chief financial officer) exceeds Fifty Million Dollars ($50,000,000.00) (the “Self-Insurance Amount”) or if Tenant can demonstrate to Landlord adequate credit worthiness for the risks self-insured as determined by Tenant’s financial statements or other objective criteria; provided, however, that Tenant shall not be released from liability hereunder by reason of said self-insurance.  The Self-Insurance Amount shall be reviewed every five (5) years, and if Landlord’s insurance advisor reasonably determines that the Self Insurance Amount should be increased, then Tenant shall increase the Self Insurance Amount to the recommended amount.\n\
            9.2.4 All such policies shall name Landlord and property manager as an Additional Insureds with respect to the operations and activities of Tenant in or in connection with Tenant’s Premises within the Buildings.\n\
            9.2.5 Each such policy shall include an undertaking by the insurer to give Landlord thirty (30) days’ prior written notice of any cancellation or change in scope or amount of coverage of such policy.  Landlord shall be furnished an endorsement to the insurance policies evidencing Tenant’s compliance with the requirements of this Section.\n\
            9.2.6 The insurance referred to in Section 9.2 above is referred to herein as “Tenant’s Insurance”.\n\
            9.3 Waiver of Subrogation.\n\
            9.3.1 Except as hereafter provided, whether the loss or damage is due to the negligence of either Landlord or Tenant, their agents or employees, or any other cause, Landlord and Tenant do each hereby release and relieve the other, their agents or employees, from responsibility for, and waive their entire claims of recovery for (i) any loss or damage to the real or personal property of either party located anywhere in the Buildings, including the Premises itself, or the Common Areas, arising out of or incident to the occurrence of any of the perils which are covered by their respective property and related insurance policies, and (ii) any loss resulting from business interruption at the Premises or loss of rental income from the Buildings, arising out of or incident to the occurrence of any of the perils which may be covered by any business interruption insurance policy or by any loss of rental income insurance policy by Landlord or Tenant.\n\
            If needed, each party shall use its best reasonable efforts to cause its insurance carriers to consent to the foregoing waiver of rights of subrogation against the other party.  Notwithstanding the foregoing, no such release shall be effective unless and to the extent the aforesaid insurance policy or policies shall expressly permit such a release or contain a waiver of the carrier's right to be subrogated.\n\
            10. SURRENDER OF PREMISES; HOLDOVER TENANCY.\n\
            10.1 Surrender. At the expiration or termination of this Lease, Tenant shall surrender immediate possession of the Premises in as good condition as when delivered to Tenant, reasonable wear and tear excepted.  At Landlord’s option, Tenant shall pay the costs to remove any Tenant Improvements, fixtures or equipment and the costs of any repairs or modifications to the Premises resulting for Tenant's use and occupancy, including repairs removal or replacement of walls, floor coverings, ceiling, cabinetry, plumbing, electrical, storefront, signage and parking.\n\
            10.2 Holding Over.  If, without the execution of a new Lease or a written extension of this Lease, and with the consent of Landlord, Tenant shall hold over after the expiration of the term of this Lease, then Tenant shall be deemed to be occupying the Premises as a Tenant from month-to-month, which tenancy may be terminated as provided by law.  If Tenant shall fail to surrender the Premises upon the termination of this Lease without the prior written consent of Landlord, then in addition to any other liabilities to Landlord resulting therefrom, Tenant shall and does hereby agree to indemnify and hold Landlord harmless from any loss or liability resulting from such failure, including, but not limited to, any claims made by any succeeding Tenant founded on such failure.\n\
            11. ACCEPTANCE OF PREMISES AND WAIVERS.\n\
            11.1 Acceptance of Premises.  By taking possession of the Premises, Tenant formally accepts the same and acknowledges that it is in the condition called for by this Lease, which is \"AS IS\" condition, subject to latent defects, except as may be modified by Section 3, if any.\n\
            11.2 Tenant Waives Damages.  Tenant hereby waives any claim for damages, including loss of business, resulting from the exercise by Landlord of its rights under this Lease, unless caused by negligence or willful misconduct of Landlord or its agents or contractors.\n\
            11.3 Mutual Indemnity.   Subject to the limitations contained in Section 9.3, above, Landlord and Tenant shall each indemnify, defend and hold harmless the other against and from any and all claims, loss, cost and expense resulting from their own respective negligent acts and omissions or the negligent acts and omissions of their respective agents or employees.\n\
            12. LANDLORD'S RESPONSIBILITY.  Landlord shall be responsible, at its own cost and expense, and without reimbursement through Operating Expenses for all repairs to structural elements of the roof (but not surface, plywood or membrane), foundation, floor slab, structural columns and sidewalls to the Medical Office buildings.\n\
            Landlord shall also be responsible for maintaining the Common Areas in good condition and repair and in accordance with standards maintained in connection with quality professional office buildings in the Highline Community Hospital area.\n\
            13. ASSIGNMENT AND SUBLETTING.\n\
            13.1 Landlord's Consent Required.  Tenant shall not assign or encumber any or all of its interest in this Lease or the Premises, or sublease all or any part of the Premises, or allow any other person or entity to occupy or use all or any part of the Premises, without first obtaining Landlord’s consent, which consent which shall not be unreasonably withheld for tenants meeting Landlord’s then-existing reasonable standards for creditworthiness and use.  No assignment or sublease shall release Tenant from the obligation to perform all obligations under this Lease.  Any assignment, encumbrance or sublease without Landlord’s written consent shall be voidable and at Landlord’s election shall constitute a default.  Any sublease shall terminate at least one (1) day prior to the Lease End Date set forth in Section 1.5.\n\
            13.2 Sublease Rent.  As a condition to Landlord’s consent to any sublease, such sublease shall provide that it is subject and subordinate to this Lease and to all mortgages; that Landlord may enforce the provisions of the sublease, including collection of rent; that in the event of termination of this Lease for any reason, including without limitation a voluntary surrender by Tenant, or in the event of any reentry or repossession of the Premises by Landlord, Landlord may, at its option, either (1) terminate the sublease or (2) take over all of the right, title and interest of Tenant, as sublessor, under such sublease, in which case such sublessee shall attorn to Landlord, but that nevertheless Landlord shall not (1) be liable for any previous act or omission of Tenant under such sublease, (2) be subject to any defense or offset previously accrued in favor of the sublessee against Tenant, or (3) be bound by any previous modification of any sublease made without Landlord’s written consent, or by any previous prepayment by sublessee of more than one month’s payment of Base Monthly Rent.  No consent to an assignment, encumbrance or sublease shall constitute a further waiver of the provisions of this Section 13.\n\
            13.3 Continued Responsibility.  The joint and several liability of Tenant and any Guarantor and any successor in interest of Tenant (by assignment or otherwise), and the due performance of the obligations of this Lease on Tenant’s part to be performed or observed, shall not in any way be discharged, released or impaired by any (a) agreement that modifies any of the rights or obligations of the parties under this Lease, (b) stipulation that extends the time within which an obligation under this Lease is to be performed, (c) waiver of the performance of an obligation required under this Lease, or (d) failure to enforce any of the obligations set forth in this Lease.\n\
            13.4 Affiliated Assignment.  If Tenant is a partnership, a withdrawal or change, voluntary, involuntary or by operation of law of any 25% or greater partner, or the dissolution of the partnership, shall be deemed a voluntary assignment.  If Tenant consists of more than one person, a purported assignment, voluntary or involuntary or by operation of law from one person to the other in excess of 25% shall be deemed a voluntary assignment.  If Tenant is a corporation, any dissolution, merger, consolidation or other reorganization of Tenant, or sale or other transfer of a controlling percentage of the capital stock of Tenant, or the sale of at least 25% of the value of the assets of Tenant shall be deemed a voluntary assignment.  The phrase “controlling percentage” means ownership of and right to vote stock possessing at least 25% of the total combined voting power of all classes of Tenant’s capital stock issued, outstanding and entitled to vote for election of directors.  The requirements of this Section 13 shall not apply to corporations, the stock of which is traded through an exchange or over the counter.  Landlord hereby consents to an assignment of this Lease, or a subletting of all or part of the Premises, to (a) the parent of Tenant or to a wholly-owned subsidiary of Tenant or of such parent, (b) any corporation or other entity into which or with which Tenant may be merged or consolidated, provided that the net worth of the resulting entity is at lease equal to the greater of (i) the net worth of Tenant on the date hereof, or (ii) the net worth of Tenant immediately prior to such merger or consolidation, or (c) any entity to which Tenant sells all or substantially all of its assets, provided that such entity expressly assumes all of Tenant’s obligations hereunder.  Transfer of all or any portion of the ownership of stock in Tenant shall not be deemed an assignment of this Lease if such transfer is made pursuant to or in connection with an initial public offering or any subsequent offering of the stock of Tenant, or once the stock of Tenant is publicly traded on a recognized public stock exchange.  Landlord agrees that its recapture or lease termination rights set forth elsewhere in this Section 13 shall not apply to or arise in connection with any transaction described in this Section 13.4.  Landlord hereby consents to the subletting of portions of the Premises from time to time to a maximum of three (3) doctors or other healthcare professionals.  At anytime upon Landlord’s request, Tenant shall provide to Landlord the names and office being used by any such subtenants.  Nothing herein shall release or limit Tenant’s liability under this Lease.\n\
            13.5 Landlord’s Rights.  One Hundred percent (100%) of any consideration received by Tenant from its subtenants in excess of the Rent payable by Tenant to Landlord under this Lease shall be paid to Landlord, or any sums to be paid by an assignee to Tenant in consideration of the assignment of this Lease shall be paid to Landlord.  Tenant shall be entitled to deduct from such excess amounts its reasonable, market leasing commissions and tenant improvement costs, provided that the same shall be amortized over the term of the sublease or assignment.  In lieu of granting consent to any proposed assignment, subletting or other transfer for which Tenant is required to obtain Landlord’s consent, Landlord reserves the right to terminate this Lease or, in the case of subletting of less than all the Premises, to terminate this Lease with respect to such portion of the Premises, as of the proposed effective date of such assignment, subletting or other transfer, in which event Landlord may enter into the relationship of landlord and tenant with such proposed transferee.  Landlord’s recapture right pursuant to the foregoing sentence shall not apply to a sublease if (a) the term of the sublease ends at least 1 year prior to the end of the term of the Lease and contains no extension rights, and (b) the total rentable area subleased, including the sublease at issue, will be less than 80% of the Premises.  The foregoing recapture right shall also not apply to a transfer permitted in Section 13.4 above.  Furthermore, if Landlord opts to exercise its recapture right pursuant to this paragraph, Tenant may upon receipt of such notice withdraw its request to assign or sublease and this Lease shall continue in full force.  If Tenant requests Landlord to consent to a proposed assignment or subletting, Tenant shall pay to Landlord, whether or not consent is ultimately given, $100 or Landlord’s reasonable attorney’s fees incurred in connection with such request, which shall not exceed $1,000 per assignment or sublease, whichever is greater.\n\
            13.6 Involuntary Assignment.  No interest of Tenant in this Lease shall be assignable by involuntary assignment through operation of law (including without limitation the transfer of this Lease by testacy or intestacy).  Each of the following acts shall be considered an involuntary assignment:  (a) if Tenant is or becomes bankrupt or insolvent, makes an assignment for the benefit of creditors, or institutes proceedings under the Bankruptcy Act in which Tenant is the bankrupt; or if Tenant is a partnership or consists of more than one person or entity, if any 25% or greater partner of the partnership becomes bankrupt or insolvent, or makes an assignment for the benefit of creditors; or (b) if a writ of attachment or execution is levied on this Lease; or (c) if an any proceeding or action to which Tenant is a party, a receiver is appointed with authority to take possession of the Premises.  An involuntary assignment shall constitute a default by Tenant and Landlord shall have the right to elect to terminate this Lease, in which case this Lease shall not be treated as an asset of Tenant.\n\
            14. OWNERSHIP OF IMPROVEMENTS AND FIXTURES.  All improvements, including air conditioning equipment, lighting fixtures, floor coverings, cabinets, sinks and other interior improvements, which may be installed in the Premises and which in any manner are attached to the floors, walls or ceilings of the Premises, shall remain with the Premises upon termination of this Lease, subject to the terms of Section 10.1, except for Tenant’s trade fixtures, personal property and proprietary items.\n\
            15. DESTRUCTION OR PUBLIC TAKING OF PREMISES.\n\
            15.1 Public Taking.\n\
            15.1.1 Eminent Domain; Whole. If the whole of the Premises shall be taken by any public authority under the power of eminent domain, then the term of this Lease shall cease as of the day possession is taken by such public authority and the Rent shall be paid up to that date.\n\
            15.1.2 Eminent Domain; Part.  If only a part of the Premises shall be taken under eminent domain and the remainder of the Premises not so taken can, in Landlord’s reasonable opinion, be made tenantable for the purposes for which Tenant has been using the Premises, then this Lease shall continue in full force and effect, as to the remainder of the Premises and all of the terms herein provided shall continue in effect except that the Base Rent shall be reduced in proportion to the amount of the Premises taken.  Landlord shall, at its expense, make all necessary repairs and alterations to the Premises required by such taking.\n\
            15.1.3 Termination by Parties.  If more than fifty percent (50%) of the Premises, the Buildings or the Property shall be so taken, then either Landlord or Tenant may, by written notice to the other delivered on or before the date of surrendering possession to the public authority, terminate this Lease.\n\
            15.1.4 Damages Belong to Landlord.  Damages awarded for such taking shall belong to and be the property of Landlord, whether such damages shall be awarded as compensation for diminution in the value of the leasehold or to the fee of the Premises; provided, however, that Tenant shall be entitled to any award made to it as a result of business income or value loss.\n\
            15.2 Destruction of Premises.\n\
            15.2.1 Repair and Abatement of Rent.  If the Premises are significantly damaged in whole or in part by a casualty, the Base Rent shall be abated (prorated as of the date of occurrence of a casualty) until restoration is completed in the proportion that the gross income (as defined by federal income tax accounting principles) from the Premises bears to the  gross income from the Premises during the most comparable period of the immediately preceding calendar year.  Tenant may continue the operation of its business on the Premises during any such period to the extent reasonably practicable from the standpoint of prudent business management.  Except for the abatement of Base Rent hereinabove provided, Tenant shall not be entitled to any compensation or damages for loss of business or for any inconvenience or annoyance occasioned by any damage, destruction, repair, or restoration.\n\
            15.2.2 Termination by Parties.  If so much of the Building is damaged by fire or other casualty as to become substantially untenantable or is otherwise so destroyed that Landlord desires to discontinue the operation of the Building, then Landlord or Tenant may terminate this Lease by giving notice to that effect to the other within thirty (30) days after such damage or destruction.  If this Lease is not so terminated, the Premises shall be repaired and restored promptly by Landlord.\n\
            If the repairs require more than 180 days to complete, as reasonably determined by Landlord within forty-five (45) days following the date of such damage or destruction, or if such repairs cannot be made under applicable laws, this Lease may be terminated at the option of either Landlord or Tenant, upon thirty (30) days' written notice given to the other party within twenty (20) days following Landlord’s written notice to Tenant setting forth the anticipated duration of such repairs and/or whether repairs may be made under applicable laws.  If a total or partial destruction of the Premises or the Building in which the Premises are located occurs during the last year of the Lease Term, Tenant may terminate this Lease upon thirty (30) days' written notice given to Landlord within thirty (30) days following the date of such total or partial destruction.\n\
            16.  DEFAULT AND REMEDIES.\n\
            16.1 Default By Tenant.  The occurrence of any one of the following events shall constitute a material breach and default under this Lease by Tenant:\n\
            16.1.1 Tenant shall have failed to pay an installment of Rent, where such failure shall continue for a period of five (5) days after it is due.\n\
            16.1.2 Tenant shall have failed to deliver documents required under this Lease within the time periods specified, where such failure shall continue for a period of ten (10) days after written notice from Landlord.\n\
            16.1.3 There shall be a default of any condition, covenant, agreement or other obligation on the part of Tenant to be performed, and such default shall continue for a period of more than thirty (30) days after written notice by Landlord to Tenant specifying the default.  If the nature of such default is such that it cannot reasonably be cured within such 30-day period, Tenant shall not be deemed to be in default if Tenant shall within the 30-day period commence such cure and thereafter diligently prosecute the same to completion.\n\
            16.1.4 Tenant commences any bankruptcy, reorganization or insolvency proceeding, or other proceeding under any federal, state or other law for the relief of debtors or Tenant fails to obtain the dismissal, within sixty (60) days after the commencement thereof, of any bankruptcy, reorganization or insolvency proceeding.\n\
            16.2 Remedies.  In the event of any default by Tenant, Landlord shall have the following rights and remedies, which shall be cumulative:\n\
            16.2.1 To sue for Rent or any amounts due hereunder, including any short fall in Base Rent and Operating Expenses between this Lease and the Lease for the Premises obtained from a successor Tenant.\n\
            16.2.2 To remedy any nonmonetary default of Tenant and to enter upon the Premises to do any work or other things therein, and in such event all reasonable expenses of Landlord in remedying such default shall be payable by Tenant to Landlord on demand.\n\
            16.2.3 To terminate this Lease by thirty (30) days’ written notice thereof to Tenant.\n\
            16.2.4 If the Landlord elects not to terminate this Lease due to Tenant's default, Landlord may maintain Tenant's right to possession and continue the Lease in effect whether or not Tenant has abandoned the Premises.  In its reasonable judgement, Landlord may relet the Premises and Tenant and any Guarantor, shall be liable for any short fall of Base Rent and Operating Expenses between this Lease and the subsequent lease.\n\
            16.3 Reentry.  In the event of any default by Tenant, Landlord shall also have the right, without terminating this Lease, to reenter the Premises and to remove all persons and property from the Premises and take whatever actions may be necessary or advisable to relet, protect or preserve the Premises.  Any property so removed may be stored in a public warehouse or other suitable place or otherwise disposed of in Landlord's discretion at the expense and for the account of Tenant.  Landlord shall not be responsible for any damages or losses suffered by Tenant as a result of such reentry, removal, storage or other disposition. No action shall be construed as an election to terminate this Lease unless a written notice of such intention is given to Tenant or unless the termination thereof be decreed by a court of competent jurisdiction.  In case of such reentry, Landlord may relet the Premises upon such reasonable terms as it deems appropriate and for a term which may expire either before or after the expiration of the Lease Term.  Upon reletting Tenant shall be immediately liable to pay to Landlord the cost and expense of reletting and of such alterations and repairs as may be incurred by Landlord in readying the Premises for reletting, including any real estate commission or tenant improvements or Tenant Improvement Allowance applicable to the unexpired term of this Lease.\n\
            16.4 Interest.  Any amount due from either party to the other under this Lease which is not paid when due, shall bear interest at the rate of twelve percent (12%) per annum (“Interest Rate”) from the date such amount was originally due to and including the date of payment.  Interest shall apply to Base Rent and Operating Expenses from the primary due date, which is typically the first day of each month.\n\
            16.5 Late Charges.  Tenant acknowledges that late payment by Tenant of Base Rent, Percentage Rent, Additional Rent or other sums due hereunder will cause Landlord to incur costs not contemplated by this Lease, the exact amount of which would be extremely difficult and impractical to ascertain.  Therefore, in the event Tenant shall fail to pay any installment of Base Rent, or any Additional Rent or due hereunder within ten (10) days after such sum is due, Tenant shall pay to Landlord as Additional Rent a late charge equal to five percent (5%) of each such installment or other sum due.  A Fifty Dollar ($50.00) charge will be paid by the Tenant to the Landlord for each check returned “NSF” or otherwise rejected, in addition to the late charge.  Interest shall apply to late charges beginning on the date the late charges may be imposed.\n\
            16.6 Default By Landlord. Landlord shall not be deemed to be in default hereunder unless Landlord shall fail to perform any act required by Landlord by this Lease, and such failure to perform continues for thirty (30) days after written notice from Tenant to Landlord specifying the nature of such default.  If the nature of Landlord's obligation is such that more than thirty (30) days is required for performance, then Landlord shall not be in default if Landlord commences performance within such thirty (30) days and diligently prosecutes the same to completion.  In no event shall Tenant be entitled to terminate this Lease by reason of Landlord's default except pursuant to the judgment of a court of competent jurisdiction providing for such termination.\n\
            17. TITLE AND POSSESSION.\n\
            17.1 Title and Possession.  Landlord represents and warrants that Landlord has legal title to the Premises and has the right to make this Lease.  Upon paying the rents and keeping the covenants and terms of this Lease on its part to be kept and performed, Tenant shall have uninterrupted possession during the continuance of this Lease, without interference by Landlord or anyone claiming through Landlord.  During the sixty (60) days prior to the expiration of the Term or any extension thereof, Landlord or its agents may advertise the availability of the Premises and show the Premises to prospective tenants during business hours.\n\
            17.2 Landlord's Right to Inspect.  Landlord may at reasonable times during Tenant's business hours, and after so advising Tenant, enter the Premises for the purpose of examining and of making repairs, but not so as to interfere with Tenant's business.  Landlord shall provide 24 hours' notice of inspection except in the case of an urgent situation such as a water or gas leak.  Tenant shall provide the Landlord or its property manager with a key to the Premises.\n\
            18. SUBORDINATION, NONDISTURBANCE AND ATTORNMENT.\n\
            18.1 Subordination.  Upon request of Landlord, and any mortgagee or beneficiary of Landlord, Tenant will in writing subordinate its rights hereunder to the lien of any mortgage or deed of trust in force against all or any part of the Property, without charge to the Landlord or its lender.  Any such subordination shall be subject to the condition that such mortgagee or beneficiary enters into a written agreement with Tenant, in recordable form, binding upon the successors and assigns of the parties thereto, by the terms of which such mortgagee or beneficiary agrees:  (a) not to disturb the possession and other rights of Tenant under this Lease so long as Tenant continues to perform its obligations hereunder; (b) in the event of acquisition of title, or coming into possession, by said mortgagee or beneficiary, through foreclosure proceedings, deed in lieu of foreclosure or otherwise, to accept Tenant as tenant of the Premises under the terms and conditions of this Lease and to perform all of Landlord's obligations under the terms of this Lease accruing after such acquisition of title or coming into possession.  Failure of Tenant to execute any statements or instruments necessary or desirable to effectuate this Section 18 within fifteen (15) days after written request by Landlord to do so shall constitute a default under this Lease.\n\
            18.2 Attornment.  In the event any proceedings are brought for foreclosure, or in the event of the exercise of the power of sale under any mortgage or deed of trust made by Landlord covering the Premises, Tenant shall attorn to the purchaser and recognize the purchaser as Landlord under this Lease; provided that the purchaser shall be obligated to acquire and accept the Premises subject to this Lease and to perform all of Landlord's obligations under the terms of this Lease accruing after such acquisition of title or coming into possession.\n\
            18.3 Tenant's Estoppel Certificate.  Tenant, within fifteen (15) days from receipt of Landlord's written request, shall execute, acknowledge and deliver to Landlord a written statement (\"Tenant's Certificate\") certifying to the extent applicable:  (a) that this Lease is in full force and effect, without modification (or, if there have been modifications, that the same is in full force and effect as modified and stating the modifications); (b) that there are no uncured defaults in Landlord's performance and that Tenant has no right of offset, counterclaim or deduction against Rent; (c) the dates to which the Rent has been paid; and (d) any other matters reasonably requested by Landlord.  Failure of Tenant to execute and deliver Tenant's Certificate shall constitute, at Landlord's option, either (i) a Default under this Lease; or (ii) acceptance of the Premises by Tenant and Tenant's acknowledgement that the statements referenced above are true and correct, without exception.\n\
            19. MISCELLANEOUS.\n\
            19.1 Notices. Any notice or document required or permitted to be delivered hereunder from one party to the other shall be in writing and shall be deemed given when personally delivered, delivered by facsimile with prompt confirmation of receipt by telephone or delivered by private courier service (such as UPS or Federal Express) or three (3) days after being deposited in the United State mail, in registered or certified form, return receipt requested, to the other party's address or facsimile number set forth below or such other address or facsimile number as shall have been last designated by notice in writing from one party to the other.\n\
            If to Landlord, to: {notice_landlord}\n\
            With a copy to: {notice_copy}\n\
            If to Tenant, To: {notice_tenant}\n\
            The address to which any notice, demand or other writing may be given, made or sent to either party may be changed by written notice given by such party as above provided.\n\
            19.2 Parking.  Tenant agrees to control the use of parking stalls by its patients, employees, visitors and agents to areas designated or requested by Landlord.  Tenant shall cooperate with other tenants of the Buildings to achieve mutual benefit and harmony with regard to use of the parking lot and driveways.  Parking shall be for the exclusive use of patrons, invitees and employees of Tenant and other occupants of the Buildings, unless otherwise required by law. Landlord shall maintain, repair and adequately light the parking areas.\n\
            19.3 Limitation of Liability.  In consideration of the benefits accruing hereunder, Tenant covenants and agrees that, in the event of any actual or alleged failure, breach or default hereunder by Landlord, Tenant's sole and exclusive remedy shall be against Landlord’s interest in the real estate upon which the Premises are located, including rents and profits, and any insurance proceeds arising from such failure, breach or default, but neither Landlord, nor any of its partners or its manager shall be personally liable or responsible for any failure, breach or default of Landlord under this Lease.  Landlord or Tenant shall not take any action against the manager or any individual partner, member, shareholder or manager, or against the assets of any individual partner, member, manager or shareholder of either party; provided, however, that nothing contained herein shall impair any rights of Landlord under any separate guaranty of Tenant’s obligations under this Lease\n\
            19.4 Events Beyond Control.  Landlord and Tenant shall not be deemed in default with respect to the performance of any of the terms, conditions and covenants of this Lease if Landlord's or Tenant's failure to perform shall be due to any strike, lockout, war, sabotage, governmental control or regulations, or Act of God or other cause beyond the control of the Landlord or Tenant, providing such cause is not due to the willful act or neglect of the Landlord or Tenant; and provided further that the foregoing shall not excuse Tenant’s failure to pay all Rent owing hereunder on a timely basis.\n\
            19.5 Brokerage.   Landlord is represented by Azose Commercial Properties Inc.. Neither party has dealt with any real estate broker with respect to this Lease except for the aforementioned, and no other broker is in any way entitled to any broker's fee or other payment in connection with this Lease.  Tenant shall indemnify and defend Landlord against any claims by any other broker or third party for any payment of any kind in connection with this Lease. \n\
            19.6 Attorneys' Fees.  In the event of litigation between Landlord and Tenant in connection with this Lease, reasonable attorneys' fees, court costs and expenses of litigation incurred by the party prevailing in such litigation shall be borne by the nonprevailing party, unless provided otherwise in this Lease.\n\
            19.7 Rent Tax.  In the event that any governmental authority imposes a tax, charge, assessment or other imposition upon tenants in general which is based upon the rents payable under this Lease, Tenant shall pay the same to the governmental authority or to Landlord if Landlord is responsible to collect the same for remittance.  Nothing shall be deemed to obligate Tenant with respect to any income, inheritance or succession tax.\n\
            19.8 Landlord’s Cooperation.  Landlord will cooperate with Tenant in all matters relative to the Premises, including required municipal consents and permits, and will execute all papers proper or necessary in connection therewith; provided, however, that such cooperation shall be without cost to Landlord.\n\
            19.9 Miscellaneous Provisions.\n\
            19.9.1  If any provision of this Lease shall be held to be invalid, illegal or unenforceable, the remaining provisions shall in no way be affected or impaired thereby.\n\
            19.9.2  All provisions of this Lease have been negotiated by both parties at arms' length and neither party shall be deemed the scrivener of this Lease.  The Lease shall not be construed for or against either party by reason of the authorship of any provision hereof.\n\
            19.9.3  This instrument shall merge all undertakings, representations, understandings, and agreements, whether oral or written, between the parties with respect to the Premises, and the provisions of this Lease and shall constitute the entire lease unless modified by both parties in writing.\n\
            19.9.4  Subject to the limitations contained in Section 13, above, and Section 19.9.5, below, this instrument shall also bind and benefit the heirs, legal representatives, assigns, and successors of the respective parties.  This instrument shall not become binding upon the parties until it has been executed by both Landlord and Tenant.\n\
            19.9.5 The term \"Landlord\" as used in this Lease, so far as Landlord’s covenants or obligations are concerned, shall be limited to mean and include only the owner or owners at the time in question of the Premises; and in the event of any transfer or transfers of title thereto, Landlord herein named (and in case of any subsequent transfers or conveyances, the then grantor) shall be automatically freed and relieved from and after the date of such transfer or conveyance of all liability for performance of any covenants or obligations of Landlord to be performed thereafter.\n\
            19.9.6  Time is of the essence of this Lease.\n\
            19.9.7  Whenever herein the singular number is used, the same shall include the plural, and the neuter gender shall include the feminine and masculine genders.\n\
            19.9.8  Attached to this Lease are:\n{attached}\n\
            IN WITNESS WHEREOF, Landlord and Tenant have executed this Lease on the dates indicated in the notarization blocks.\n\
            {sign}"

variables = {
    'company': "HIGHLINE PROFESSIONAL BUILDING",
    'date': '10',
    'month_year': 'September 2023',
    'landlord': 'HIGHLINE PROFESSIONAL BUILDING ASSOCIATES LIMITED PARTNERSHIP, a Washington limited partnership',
    'tenant': 'DANIEL W. GOTTLIEB, MD.',
    'tenant_name_address': 'Daniel W. Gottlieb, MD\n16122 8th Avenue SW, Suite D1\nBurien, WA 98166\nPhone:    \nEmail: drdgottlieb@gmail.com',
    'premises_address': 'Highline Professional Building\n16122 8th Avenue SW, Suite D1\nBurien, WA 98166',
    'lease_term': '3 years    (Section 4)',
    'commencement_date': 'May 1, 2024    (Section 2.4)',
    'lease_end': 'April 30, 2027    (Section 4)',
    'base_rent': 'See Exhibit E, Additional Provisions    (Section 5)',
    'additional_rent': 'NA',
    'termination_option': 'See section 4.1',
    'option_rent': 'NA',
    'tenant_use': 'General office and medical health facility    (Section 6.1)',
    'security_deposit': '$ 2,907.56    (Section 5.3)',
    'prepaid_rent': '$ 2907.56',
    'buildings': 'Buildings "D" and "E" of the Medical Park, which Buildings contain a total of approximately 14,468 square feet and are located at 16122-8th Avenue SW, Seattle, Washington 98166.',
    'premises': '1,500 sq. ft.',
    'base_rent': 'May 1, 2024 - October 31, 2024    $ 2,907.56 per month full service\n\
                  November 1, 2024 - October 31, 2025    $ 2,994.79 per month full service\n\
                  November 1, 2025 - October 31, 2026    $ 3,084.63 per month full service\n\
                  November 1, 2026 - October 31, 2027    $ 3,177.17 per month full service',
    'pay_to': 'Azose Commercial Properties, Inc.\nc/o Highline Professional Building Associates LP\n8451 SE 68th St 200\nMercerIsland, Washington 98040',
    'pro_rata1': '10.71% (1,550 sq.ft of 14,468 sq.ft)',
    'pro_rata2': '10.71% (1,550 sq.ft of 14,468 sq.ft)',
    'operating_expenses_date': 'By April 1 of each year thereafter',
    '5_4': 'Prepaid Rent. Tenant has not prepaid any Base Rent.',
    'notice_landlord': 'Highline Professional Building LP\nc/o Mark O\'Shea\n8451 SE 68th St #200\nMercer Island, WA 98040',
    'notice_copy': 'Azose Commercial Properties, Inc.\nC/o Highline Professional Building LP\n8451 SE 68th St #200\nMercer Island, WA 98040',
    'notice_tenant': 'Daniel W. Gottlieb, MD\n16122 8th Ave SW Suite D1\nBurien, WA 98166',
    'attached': 'Exhibit A - Legal Description\n\
                Exhibit B - Site Plan Identifying Premises\n\
                Exhibit C - Regarding any special clauses for the Lease, if any\n\
                Exhibit D - Rules and Regulations promulgated by lessor and subject to change or modification at a later time.\n\
                Exhibit E - Additional Privisions\n\
                Exhibit F - Landlord\'s Work',
    'sign': 'TENANT:      LANDLORD:\n\
            Daniel W. Gottlieb, MD      HIGHLINE PROFESSIONAL BUILDING LIMITED PARTNERSHIP, a Washington limited partnership\n\
            By: ________________________      By: HIGHLINE GENERAL, LLC, a washington limited liability company\n\
            Date: ________________________      Date: ________________________\n\
            THIS LEASE SHALL BE NULL AND VOID UNLESS SIGNED BY BOTH LANDLORD AND TENANT NOT LATER THAN October 31, 2023.'
}

lease = str.format(template, **variables)
print(lease)